fixtures:
  repositories:
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    git: "https://github.com/puppetlabs/puppetlabs-git"
    
